### ISSUE TITLE
Error reading SFS file in ngsStat

### ISSUE THREAD

**Issue by DiedeMaas** [mfumagalli/ngsPopGen#5]
Hi,

I would like to calculate expected heterozygosity for my populations using .saf files and ngsStat, but I keep getting the error: "Possible error reading SFS, binary file might be broken". 

I have followed the ngsTutorial in creating the .sfs and .saf files required, and haven't had this issue in previous analyses. I've seen online that someone else having this problem had to use realSFS to generate the SFS files, but I have been using that from the beginning.

The command where the error occurs (from the ngsTutorial):
$NGSTOOLS/ngsPopGen/ngsStat -npop 1 -postfiles Results/PEL.saf -nsites $N_SITES -nind 20 -outfile Results/PEL.stats.txt

Unfortunately, my saf.gz file is too big to be added on here. I have included my SFS file in text format, if that is any help.
[MIS01.sfs.txt](https://github.com/mfumagalli/ngsPopGen/files/463586/MIS01.sfs.txt)

I hope this can be solved!
Diede

**Comment by mfumagalli** [comment]
Hi Diede,

usually that error is generated when the sample size and number of sites
you specify are not correct or, in other words, not compatible with the
dimensions of saf files.

It seems that you have 8 diploid samples for your .sfs.txt file, is that
what you specified in your command line?

Be sure to use the latest versions of both ANGSD and ngsTools (git pull).

Also, be aware that you can use ANGSD to compute many statistics, like pi
or theta that can be proxies for genetic diversity. ANGSD has a better
implementation that ngsTools. I personally use ngsTools only for PCA now.

Finally, remember that folded spectrum is not supported anymore, in case
that was what you set.

Please let me know if setting the correct nr of sites and samples didn't
solve your issues.

Thanks

Best

Matteo
