### ISSUE TITLE
ngsStat Floating point exception (core dumped)

### ISSUE THREAD

**Issue by madzayasodara** [mfumagalli/ngsPopGen#9]
Hello, 
I'm trying to use ngsStat by doing:
`./ngsStat -npop 1 -postfiles file.saf -nind 11 -outfile file.stat`
where my .saf (out of angsd) looks like:
```
NC_007897.1     2       0.000000        -5.094189       -10.313600      -15.673835      -21.194906      -26.905237      -32.847622      -39.091530      -45.764591      -53.156807      -62.342842      -73.078079      -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf
NC_007897.1     3       0.000000        -5.217402       -10.582065      -16.106823      -21.804443      -27.695183      -33.814251      -40.223988      -47.043053      -54.543686      -63.845039      -75.157547      -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf
NC_007897.1     4       0.000000        -5.217465       -10.582220      -16.107111      -21.804922      -27.695948      -33.815476      -40.226013      -47.046764      -54.552528      -63.910259      -75.850700      -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf
NC_007897.1     5       0.000000        -5.217465       -10.582220      -16.107111      -21.804922      -27.695948      -33.815476      -40.226013      -47.046764      -54.552528      -63.910259      -75.850700      -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf    -inf
```

but I'm getting the error:

`Floating point exception (core dumped)`

Any ideas what could be wrong?

**Comment by mfumagalli** [comment]
Hi Madza! 
I think you missed the -nsites option.
But more importantly, why are you using ngsStat? Most of these statistics are much better implemented in ANGSD so I encourage you to use ANGSD instead of ngsStat.

**Comment by madzayasodara** [comment]
Hummm I get another error when I use the -nsites
`-> Possible error reading SFS, binary file might be broken...`
Yeah, I'm using angsd for most stuff, but it doesn't calc het in a window does it? Or fixed sites between 2pops? Guess I have to write something to do it... thxs!

**Comment by mfumagalli** [comment]
Usually you get that error when the -nind option is in conflict with the actual dimensions of .saf files. Did you fold the data? ngsTools doesn't really support folded data. Let me know.

**Comment by mfumagalli** [comment]
closed since no further requests for made
